// oracle sql db schema


CREATE TABLE ACCOUNT_SUB_TYPES{
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    ACCOUNT_TYPE VARCHAR2(4) NOT NULL,
    GENDER VARCHAR2(8) NOT NULL,
    ACCOUNT_SUB_TYPE_NAME VARCHAR2(128) NOT NULL,
    ACCOUNT_SUB_TYPE_CODE VARCHAR2(32) NOT NULL UNIQUE,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_DELETED IN (0,1)),
    IS_ENABLED    NUMBER(1) DEFAULT 1 NOT NULL CHECK (ENABLED IN (0,1)),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
    CONSTRAINT CHK_ACCOUNT_SUB_TYPES_IS_DELETED CHECK (IS_DELETED IN (0,1)),
    CONSTRAINT CHK_ACCOUNT_SUB_TYPES_IS_ENABLED CHECK (IS_ENABLED IN (0,1)),
    CONSTRAINT CHK_ACCOUNT_SUB_TYPES_ACCOUNT_TYPE CHECK (ACCOUNT_TYPE IN ('IFB', 'CB')),  
    CONSTRAINT CHK_ACCOUNT_SUB_TYPES_GENDER CHECK (GENDER IN ('MALE', 'FEMALE', 'OTHER')),
}
