-- ACCOUNT_CATEGORIES
CREATE TABLE ACCOUNT_CATEGORIES (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,

    ACCOUNT_TYPE VARCHAR2(4) NOT NULL,
    CATEGORY_NAME VARCHAR2(128) NOT NULL,
    CBS_CATEGORY_CODE VARCHAR2(64) NOT NULL,

    DESCRIPTION VARCHAR2(512),

    IS_ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,

    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,

    CONSTRAINT UK_ACCOUNT_CATEGORIES_CBS_CODE
        UNIQUE (CBS_CATEGORY_CODE),

    CONSTRAINT CHK_ACCOUNT_CATEGORIES_ACCOUNT_TYPE
        CHECK (ACCOUNT_TYPE IN ('IFB', 'CB', 'BOTH')),

    CONSTRAINT CHK_ACCOUNT_CATEGORIES_IS_ENABLED
        CHECK (IS_ENABLED IN (0,1)),

    CONSTRAINT CHK_ACCOUNT_CATEGORIES_IS_DELETED
        CHECK (IS_DELETED IN (0,1))
);

CREATE INDEX IDX_ACCOUNT_CATEGORIES_CATEGORY_NAME
    ON ACCOUNT_CATEGORIES(CATEGORY_NAME);

CREATE INDEX IDX_ACCOUNT_CATEGORIES_ACCOUNT_TYPE
    ON ACCOUNT_CATEGORIES(ACCOUNT_TYPE);


-- ACCOUNT_PRODUCTS
CREATE TABLE ACCOUNT_PRODUCTS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,

    CBS_PRODUCT_CODE VARCHAR2(64) NOT NULL,
    PRODUCT_NAME VARCHAR2(128) NOT NULL,
    PRODUCT_TAG_LINE VARCHAR2(128) NOT NULL,

    ACCOUNT_CATEGORY_ID RAW(16) NOT NULL,

    ACCOUNT_CURRENCY VARCHAR2(3) NOT NULL,

    MINIMUM_OPENING_BALANCE NUMBER(19,4) NOT NULL,
    MINIMUM_MAINTENANCE_FEE NUMBER(19,4) NOT NULL,
    INTEREST_FEE NUMBER(19,4) NOT NULL,

    FAQ_URL VARCHAR2(512),
    PRODUCT_FEATURES VARCHAR2(1024),

    HAS_PHYSICAL_CARD NUMBER(1) DEFAULT 0 NOT NULL,
    HAS_VIRTUAL_CARD NUMBER(1) DEFAULT 0 NOT NULL,

    PRODUCT_ICON VARCHAR2(512),
    PRODUCT_COVER_IMAGE VARCHAR2(512),

    IS_ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,

    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,

    CONSTRAINT UK_ACCOUNT_PRODUCTS_CBS_CODE
        UNIQUE (CBS_PRODUCT_CODE),

    CONSTRAINT FK_ACCOUNT_PRODUCTS_ACCOUNT_CATEGORY
        FOREIGN KEY (ACCOUNT_CATEGORY_ID)
        REFERENCES ACCOUNT_CATEGORIES(ID)
        ON DELETE CASCADE,

    CONSTRAINT CHK_ACCOUNT_PRODUCTS_HAS_PHYSICAL_CARD
        CHECK (HAS_PHYSICAL_CARD IN (0,1)),

    CONSTRAINT CHK_ACCOUNT_PRODUCTS_HAS_VIRTUAL_CARD
        CHECK (HAS_VIRTUAL_CARD IN (0,1)),

    CONSTRAINT CHK_ACCOUNT_PRODUCTS_IS_ENABLED
        CHECK (IS_ENABLED IN (0,1)),

    CONSTRAINT CHK_ACCOUNT_PRODUCTS_IS_DELETED
        CHECK (IS_DELETED IN (0,1))
);

CREATE INDEX IDX_ACCOUNT_PRODUCTS_ACCOUNT_CATEGORY_ID
    ON ACCOUNT_PRODUCTS(ACCOUNT_CATEGORY_ID);


-- ACCOUNT_OPENING_TERMS
CREATE TABLE ACCOUNT_OPENING_TERMS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,

    ACCOUNT_PRODUCT_ID RAW(16) NOT NULL,

    ACTIVATION_TIME TIMESTAMP NOT NULL,
    VERSION_LABEL VARCHAR2(128) NOT NULL,

    TERMS_AND_CONDITIONS_PATH VARCHAR2(512) NOT NULL,

    IS_ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,

    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,

    CONSTRAINT FK_ACCOUNT_OPENING_TERMS_ACCOUNT_PRODUCT
        FOREIGN KEY (ACCOUNT_PRODUCT_ID)
        REFERENCES ACCOUNT_PRODUCTS(ID)
        ON DELETE CASCADE,

    CONSTRAINT CHK_ACCOUNT_OPENING_TERMS_IS_ENABLED
        CHECK (IS_ENABLED IN (0,1)),

    CONSTRAINT CHK_ACCOUNT_OPENING_TERMS_IS_DELETED
        CHECK (IS_DELETED IN (0,1))
);

CREATE INDEX IDX_ACCOUNT_OPENING_TERMS_ACCOUNT_PRODUCT_ID
    ON ACCOUNT_OPENING_TERMS(ACCOUNT_PRODUCT_ID);

CREATE UNIQUE INDEX IDX_ACCOUNT_OPENING_TERMS_PRODUCT_VERSION
    ON ACCOUNT_OPENING_TERMS(ACCOUNT_PRODUCT_ID, VERSION_LABEL);