CREATE TABLE SEGMENTS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    CUSTOMER_GROUP VARCHAR2(50 CHAR) NOT NULL,
    CUSTOMER_GROUP_LABEL VARCHAR2(100 CHAR) NOT NULL,
    CUSTOMER_SEGMENT VARCHAR2(50 CHAR),
    CUSTOMER_SEGMENT_LABEL VARCHAR2(100 CHAR),
    CUSTOMER_SUBSEGMENT VARCHAR2(50 CHAR),
    CUSTOMER_SUBSEGMENT_LABEL VARCHAR2(100 CHAR),
    SUPERAPP_ROLE VARCHAR2(50 CHAR) NOT NULL,
    SUPERAPP_ROLE_LABEL VARCHAR2(100 CHAR) NOT NULL,
    CHECK_SUM VARCHAR2(128 CHAR) NOT NULL, -- Adjusted based on typical hash lengths
    IS_ENABLED NUMBER(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_SEGMENTS_IS_ENABLED CHECK (IS_ENABLED IN (0, 1))
);

CREATE INDEX IDX_SEGMENTS_CHECK_SUM ON SEGMENTS(CHECK_SUM);

--- ADD USERS
ALTER TABLE USERS ADD (
    CUSTOMER_GROUP VARCHAR(32),
    SUPERAPP_ROLE VARCHAR(32),
    CUSTOMER_SUBSEGMENT VARCHAR(32),
    IS_RESET_PIN NUMBER(1) DEFAULT 0,
    IS_TERMINATED NUMBER(1) DEFAULT 0,
    TERMINATION_COUNTER NUMBER(3) DEFAULT 0,
    HAS_CHANGE VARCHAR2(255)
);

--- DROP TARNSACTION DROP CONSTRAINT
ALTER TABLE CREDIT_ACCOUNT_NUMBER DROP CONSTRAINT TRANSACTIONS;

---is

-- DONATION CREATE 
CREATE TABLE DONATION_CATEGORIES (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(128) NOT NULL,
    ICON          VARCHAR2(512),
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_DELETED IN (0,1)),
    ENABLED    NUMBER(1) DEFAULT 1 NOT NULL CHECK (ENABLED IN (0,1)),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DONATION_COMPANIES (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    COMPANY_NAME        VARCHAR2(128) NOT NULL,
    COMPANY_CODE        VARCHAR2(64) UNIQUE NOT NULL,
    COMPANY_LOGO        VARCHAR2(512),
    COMPANY_DESCRIPTION VARCHAR2(1024), 
    ADDRESS      VARCHAR2(500),
    PHONE_NUMBER VARCHAR2(50),
    EMAIL        VARCHAR2(200),
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_DELETED IN (0,1)),
    ENABLED    NUMBER(1) DEFAULT 1 NOT NULL CHECK (ENABLED IN (0,1)),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP
);

CREATE TABLE DONATIONS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    DONATION_CODE VARCHAR2(100) UNIQUE NOT NULL,
    SERVICE_ID RAW(16) NOT NULL,
    COMPANY_ID  RAW(16) NOT NULL,
    CATEGORY_ID RAW(16) NOT NULL,
    TITLE VARCHAR2(256) NOT NULL,
    IS_FEATURED NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_FEATURED IN (0,1)),
    TARGET         NUMBER(19,4), 
    CURRENT_AMOUNT NUMBER(19,4),
    DONATION_DESCRIPTION VARCHAR2(1024),
    COVER_IMAGE          VARCHAR2(1000),
    START_DATE TIMESTAMP NOT NULL,
    END_DATE   TIMESTAMP,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL CHECK (IS_DELETED IN (0,1)),
    ENABLED    NUMBER(1) DEFAULT 1 NOT NULL CHECK (ENABLED IN (0,1)),
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_DONATIONS_SERVICE_ID FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES(ID),
    CONSTRAINT FK_DONATIONS_COMPANY_ID FOREIGN KEY (COMPANY_ID) REFERENCES DONATION_COMPANIES(ID),
    CONSTRAINT FK_DONATIONS_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES DONATION_CATEGORIES(ID)
);

CREATE TABLE DONATION_IMAGES (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    DONATION_ID RAW(16) NOT NULL,
    PHOTO_URL   VARCHAR2(512) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_DONATION_IMAGES_DONATION_OD FOREIGN KEY (DONATION_ID) REFERENCES DONATIONS(ID) ON DELETE CASCADE
);

CREATE TABLE BOOKMARKS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    USER_CODE VARCHAR2(64) NOT NULL,
    DONATION_ID RAW(16) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT FK_BOOKMARKS_USER_CODE FOREIGN KEY (USER_CODE) REFERENCES  USERS(USER_CODE) ON DELETE CASCADE,
    CONSTRAINT FK_BOOKMARKS_DONATION_ID FOREIGN KEY (DONATION_ID) REFERENCES DONATIONS(ID)ON DELETE CASCADE
);

-- DONATION DROP
DROP TABLE BOOKMARKS CASCADE CONSTRAINTS;
DROP TABLE DONATION_IMAGES CASCADE CONSTRAINTS;
DROP TABLE DONATIONS CASCADE CONSTRAINTS;
DROP TABLE DONATION_COMPANIES CASCADE CONSTRAINTS;
DROP TABLE DONATION_CATEGORIES CASCADE CONSTRAINTS;

-- MERCHANT CREATE TABLE
CREATE TABLE MERCHANTS(
  ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  MERCHANT_ACCOUNT_NUMBER VARCHAR2(16),
  MERCHANT_CODE VARCHAR(32) NOT NULL UNIQUE,
  MERCHANT_NAME VARCHAR(96) NOT NULL,
  SETTLEMENT_METHOD VARCHAR(8) NOT NULL,
  MERCHANT_TYPE VARCHAR(12) NOT NULL,
  CONTACT_EMAIL VARCHAR(128),
  CONTACT_PHONE VARCHAR(12),
  IS_ENABLED NUMBER(1) DEFAULT 1,
  IS_DELETED NUMBER(1) DEFAULT 0,
  CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP, 
  LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP, 
  DELETED_AT TIMESTAMP,
  CONSTRAINT CHK_MERCHANTS_IS_ENABLED CHECK(IS_ENABLED IN (0, 1)),
  CONSTRAINT CHK_MERCHANTS_IS_DELETED CHECK(IS_DELETED IN (0, 1)),
  CONSTRAINT CHK_MERCHANTS_TYPE CHECK(MERCHANT_TYPE IN ('MINI_APP', 'ECOMMERCE', 'EVENT', 'LOGISTICS')),
  CONSTRAINT CHK_MERCHANTS_SETTLEMENT_METHOD CHECK(SETTLEMENT_METHOD IN ('GL', 'DIRECT'))
);

CREATE TABLE MERCHANT_BRANCHES (
  ID                     RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  MERCHANT_ID            RAW(16) NOT NULL,
  BRANCH_CODE            VARCHAR2(32)  NOT NULL,
  BRANCH_NAME            VARCHAR2(128) NOT NULL,
  BRANCH_ADDRESS         VARCHAR2(256),
  BRANCH_OWNER           VARCHAR2(128),
  BRANCH_ACCOUNT_NUMBER  VARCHAR2(16),
  IS_ENABLED             NUMBER(1)  DEFAULT 1,
  IS_DELETED             NUMBER(1)  DEFAULT 0,
  CREATED_AT             TIMESTAMP  DEFAULT SYSTIMESTAMP,
  LAST_MODIFIED_AT       TIMESTAMP  DEFAULT SYSTIMESTAMP,
  DELETED_AT             TIMESTAMP,
  CONSTRAINT UQ_MERCHANT_BRANCHES    UNIQUE (MERCHANT_ID, BRANCH_CODE),
  CONSTRAINT CHK_MERCHANT_BRANCHES_IS_ENABLED  CHECK (IS_ENABLED  IN (0, 1)),
  CONSTRAINT CHK_MERCHANT_BRANCHES_IS_DELETED  CHECK (IS_DELETED  IN (0, 1)),
  CONSTRAINT FK_MERCHANT_BRANCHES_MERCHANT_ID FOREIGN KEY (MERCHANT_ID) REFERENCES MERCHANTS (ID),
  CONSTRAINT FK_MERCHANT_BRANCHES_BRANCH_ACCOUNT_NUMBER FOREIGN KEY (BRANCH_ACCOUNT_NUMBER) REFERENCES ACCOUNTS (ACCOUNT_NUMBER)
);

-- MERCHANT DROP TABLE
DROP TABLE MERCHANTS CASCADE CONSTRAINTS;
DROP TABLE MERCHANT_BRANCHES CASCADE CONSTRAINTS;


--- WALLET 
CREATE TABLE WALLETS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    WALLET_NAME VARCHAR2(96),
    WALLET_CODE VARCHAR2(32),
    LOGO VARCHAR2(128),
    IS_ENABLED NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHK_WALLETS_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHK_WALLETS_IS_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE TABLE WALLET_SERVICES (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    SERVICE_ID RAW(16) NOT NULL,
    WALLET_ID RAW(16) NOT NULL,
    SERVICE_TYPE VARCHAR2(6) NOT NULL,
    IS_ENABLED NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHK_WALLET_SERVICES_IS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHK_WALLET_SERVICES_IS_DELETED CHECK (IS_DELETED IN (0, 1)),
    CONSTRAINT CHK_WALLET_SERVICES_SERVICE_TYPE CHECK (SERVICE_TYPE IN ('SELF', 'AGENT', 'OTHER')),
    CONSTRAINT FK_WALLET_SERVICES_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES (ID) ON DELETE CASCADE,
    CONSTRAINT FK_WALLET_SERVICES_WALLET FOREIGN KEY (WALLET_ID) REFERENCES WALLETS (ID) ON DELETE CASCADE
);



CREATE TABLE MINI_APP_CATEGORIES (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    NAME VARCHAR2(255) NOT NULL UNIQUE,
    ICON VARCHAR2(512),
    IS_ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
    IS_DELETED NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CONSTRAINT CHK_MINI_CATEGORIES_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHK_MINI_CATEGORIES_DELETED CHECK (IS_DELETED IN (0, 1))
);

CREATE TABLE MINI_APPS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    CATEGORY_ID RAW(16) NOT NULL,
    MERCHANT_ID RAW(16), 
    SERVICE_ID RAW(16),  
    APP_NAME VARCHAR2(255) NOT NULL,
    APP_ICON VARCHAR2(512),
    APP_TYPE VARCHAR2(32) NOT NULL,
    BANNER_IMAGE VARCHAR2(512),
    URL VARCHAR2(512) NOT NULL,
    APP_VIEW_TYPE VARCHAR2(50) NOT NULL,
    IS_FEATURED NUMBER(1) DEFAULT 0,
    IS_ENABLED NUMBER(1) DEFAULT 1,
    IS_DELETED NUMBER(1) DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    LAST_MODIFIED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    DELETED_AT TIMESTAMP,
    CREDENTIAL_MERCHANT_APP_ID VARCHAR2(255),
    CREDENTIAL_FABRIC_APP_ID VARCHAR2(255),
    CREDENTIAL_SHORT_CODE VARCHAR2(100),
    CREDENTIAL_APP_SECRET VARCHAR2(255),
    CREDENTIAL_PRIVATE_KEY CLOB,
    CREDENTIAL_PUBLIC_KEY CLOB,
    CONSTRAINT FK_MINI_APPS_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES MINI_APP_CATEGORIES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_MINI_APPS_MERCHANT FOREIGN KEY (MERCHANT_ID) REFERENCES MINI_APP_MERCHANTS(ID) ON DELETE SET NULL,
    CONSTRAINT FK_MINI_APPS_SERVICE FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES(ID) ON DELETE SET NULL,
    CONSTRAINT CHK_MINI_APPS_TYPE CHECK (APP_TYPE IN ('FINANCIAL', 'NON_FINANCIAL')),
    CONSTRAINT CHK_MINI_APPS_VIEW_TYPE CHECK (APP_VIEW_TYPE IN ('BOTH', 'CB', 'IFB')),
    CONSTRAINT CHK_MINI_APPS_FEATURED CHECK (IS_FEATURED IN (0, 1)),
    CONSTRAINT CHK_MINI_APPS_ENABLED CHECK (IS_ENABLED IN (0, 1)),
    CONSTRAINT CHK_MINI_APPS_DELETED CHECK (IS_DELETED IN (0, 1))
);



CREATE TABLE MINI_APP_PAYMENTS (
    ID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
    APP_CODE VARCHAR2(100) NOT NULL,
    MERCHANT_CODE VARCHAR2(100) NOT NULL,
    MERCHANT_REFERENCE VARCHAR2(255) NOT NULL UNIQUE,
    TITLE VARCHAR2(255),
    TOTAL_AMOUNT NUMBER(18, 4) NOT NULL,
    CURRENCY VARCHAR2(10) DEFAULT 'ETB',
    FT_NUMBER VARCHAR2(24),
    TRANSACTION_REFERENCE VARCHAR2(128),
    STATUS VARCHAR2(50) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT CHK_MINI_PAYMENTS_STATUS CHECK (STATUS IN ('PENDING', 'COMPLETED', 'FAILED'))
);